# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-07-01 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import show.models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showgroup',
            name='picture',
            field=models.ImageField(default=b'/static/python/null.jpg', upload_to=show.models.upload_path_handler),
        ),
    ]
