# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_showreview_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='showgroup',
            name='site',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
