# Generated by Django 3.2.23 on 2023-11-30 03:04

from django.db import migrations, models
import show.models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0004_showgroup_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showgroup',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='showgroup',
            name='picture',
            field=models.ImageField(default='/static/python/null.jpg', upload_to=show.models.upload_path_handler),
        ),
    ]
