# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-04-18 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_classroom_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='lesson',
            field=models.IntegerField(choices=[(1, b'\xe7\xa8\x8b\xe5\xbc\x8f\xe8\xa8\xad\xe8\xa8\x88\xe8\xbc\x95\xe9\xac\x86\xe5\xad\xb8\xef\xbc\x9a\xe4\xbd\xbf\xe7\x94\xa8Scratch2.X'), (2, b'VPhyscis\xe7\x89\xa9\xe7\x90\x86\xe6\xa8\xa1\xe6\x93\xac\xef\xbc\x9a\xe4\xbd\xbf\xe7\x94\xa8Python2'), (3, b'Euler\xe6\x95\xb8\xe5\xad\xb8\xe8\xa7\xa3\xe9\xa1\x8c\xef\xbc\x9a\xe4\xbd\xbf\xe7\x94\xa8Python3')], default=0),
        ),
    ]
