# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-04-19 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20180418_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=b'', max_length=50)),
                ('first_name', models.CharField(default=b'', max_length=50)),
                ('password', models.CharField(default=b'', max_length=50)),
                ('email', models.CharField(default=b'', max_length=100)),
            ],
        ),
    ]
