# Generated by Django 3.2.23 on 2023-11-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0017_classroom_group_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='lesson',
            field=models.IntegerField(choices=[(1, '程式設計輕鬆學：使用Scratch2.X'), (2, 'VPhyscis物理模擬：使用Python2'), (3, 'Euler數學解題：使用Python3'), (4, 'VPhyscis物理模擬：建中特色課程'), (5, 'VPhyscis物理模擬：使用Python3'), (6, '機器人程式設計：使用Microbit'), (7, 'Pandas數據分析：使用Python3'), (8, 'Django網站開發：使用Python3'), (9, 'Science科學運算：使用Python3'), (10, '網路讀書會：好書共讀')], default=0),
        ),
        migrations.AlterField(
            model_name='fcontent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='fcontent',
            name='memo',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='fwork',
            name='domains',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='fwork',
            name='levels',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='fwork',
            name='title',
            field=models.CharField(max_length=250, verbose_name='討論主題'),
        ),
        migrations.AlterField(
            model_name='importuser',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='importuser',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='importuser',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='importuser',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
