# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-04-16 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='online',
            field=models.BooleanField(default=True),
        ),
    ]
