# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-04-17 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_school_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('county', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='county',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='school',
            name='zone',
            field=models.IntegerField(default=0),
        ),
    ]
