# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-04-17 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_message_messagefile_messagepoll_pointhistory_profile_visitor_visitorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='creative',
            field=models.IntegerField(default=0),
        ),
    ]
