# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-04-20 02:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_logcounter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logcounter',
            name='user_id',
        ),
    ]
