# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-04-21 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_logcounter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('approver', models.IntegerField(default=0)),
                ('memo', models.TextField()),
                ('file', models.FileField(upload_to=b'')),
            ],
        ),
    ]
