# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-06-23 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_teacherapply'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lock1',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='lock2',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='lock3',
            field=models.IntegerField(default=1),
        ),
    ]
