# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-06-30 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20180623_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lock4',
            field=models.IntegerField(default=1),
        ),
    ]
