# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-07-07 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_profile_lock4'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lock5',
            field=models.IntegerField(default=1),
        ),
    ]
