# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-07-10 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20180711_0207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message_type',
            new_name='type',
        ),
        migrations.AddField(
            model_name='messagepoll',
            name='message_type',
            field=models.IntegerField(default=0),
        ),
    ]
