# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-07-10 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20180711_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reader_id',
            field=models.IntegerField(default=0),
        ),
    ]
