# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-15 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_profile_forum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='forum',
            field=models.FloatField(default=0),
        ),
    ]
