# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-01 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='classroom',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
