# Generated by Django 3.2.23 on 2023-11-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_profile_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='teacherapply',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='IP',
            field=models.CharField(default='', max_length=20),
        ),
    ]
