# Generated by Django 4.2.8 on 2023-12-15 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0019_alter_assistant_id_alter_classroom_id_alter_cwork_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0026_remove_log_user_id_remove_pointhistory_user_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageFile',
        ),
        migrations.RemoveField(
            model_name='messagecontent',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='message',
            name='author_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='reader_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='classroom_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='messagepoll',
            name='classroom_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.RunSQL(
            "DELETE FROM account_message WHERE author_id > 0 AND author_id not in (SELECT id from auth_user)",
        ),
        migrations.RunSQL(
            "UPDATE account_message SET author_id = NULL WHERE author_id = 0",
            "UPDATE account_message SET author_id = 0 WHERE author_id = NULL",
        ),
        migrations.RunSQL(
            "DELETE FROM account_message WHERE reader_id > 0 AND reader_id not in (SELECT id from auth_user)",
        ),
        migrations.RunSQL(
            "UPDATE account_message SET reader_id = NULL WHERE reader_id = 0",
            "UPDATE account_message SET reader_id = 0 WHERE reader_id = NULL",
        ),
        migrations.RunSQL(
            "UPDATE account_message SET classroom_id = -classroom_id WHERE classroom_id < 0",
        ),
        migrations.RunSQL(
            "DELETE FROM account_message WHERE classroom_id > 0 AND classroom_id not in (SELECT id from teacher_classroom)",
        ),
        migrations.RunSQL(
            "UPDATE account_message SET classroom_id = NULL WHERE classroom_id = 0",
            "UPDATE account_message SET classroom_id = 0 WHERE classroom_id = NULL",
        ),
        migrations.RenameField(
            model_name = 'message',
            old_name = 'author_id',
            new_name = 'author',
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbox', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name = 'message',
            old_name = 'classroom_id',
            new_name = 'classroom',
        ),
        migrations.AlterField(
            model_name='message',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='teacher.classroom'),
        ),
        migrations.RenameField(
            model_name = 'message',
            old_name = 'reader_id',
            new_name = 'reader',
        ),
        migrations.AlterField(
            model_name='message',
            name='reader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbox', to=settings.AUTH_USER_MODEL),
        ),
        # ---------------------------------------------------------
        migrations.RunSQL(
            "DELETE FROM account_messagecontent WHERE message_id not in (SELECT id from account_message)",
        ),
        migrations.RenameField(
            model_name = 'messagecontent',
            old_name = 'message_id',
            new_name = 'message',
        ),
        migrations.AlterField(
            model_name='messagecontent',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='account.message'),
        ),
        migrations.RunSQL(
            "UPDATE account_messagepoll SET classroom_id = -classroom_id WHERE classroom_id < 0",
        ),
        migrations.RunSQL(
            "DELETE FROM account_messagepoll WHERE classroom_id > 0 AND classroom_id not in (SELECT id from teacher_classroom)",
        ),
        migrations.RunSQL(
            "UPDATE account_messagepoll SET classroom_id = NULL WHERE classroom_id = 0",
            "UPDATE account_messagepoll SET classroom_id = 0 WHERE classroom_id = NULL",
        ),
        migrations.RunSQL(
            "DELETE FROM account_messagepoll WHERE message_id not in (SELECT id from account_message)",
        ),
        migrations.RunSQL(
            "DELETE FROM account_messagepoll WHERE reader_id not in (SELECT id from auth_user)",
        ),
        migrations.RenameField(
            model_name = 'messagepoll',
            old_name = 'classroom_id',
            new_name = 'classroom',
        ),
        migrations.AlterField(
            model_name='messagepoll',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.classroom'),
        ),
        migrations.RenameField(
            model_name = 'messagepoll',
            old_name = 'message_id',
            new_name = 'message',
        ),
        migrations.AlterField(
            model_name='messagepoll',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.message'),
        ),
        migrations.RenameField(
            model_name = 'messagepoll',
            old_name = 'reader_id',
            new_name = 'reader',
        ),
        migrations.AlterField(
            model_name='messagepoll',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_read_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
