# -*- coding: UTF-8 -*-
county = []

def reset():
    zone = []    
    zone.append('板橋區')
    zone.append('三重區')
    zone.append('中和區')
    zone.append('永和區')
    zone.append('新莊區')
    zone.append('新店區')
    zone.append('樹林區')
    zone.append('鶯歌區')
    zone.append('三峽區')
    zone.append('淡水區')
    zone.append('汐止區')
    zone.append('瑞芳區')
    zone.append('土城區')
    zone.append('蘆洲區')
    zone.append('五股區')
    zone.append('泰山區')
    zone.append('林口區')
    zone.append('深坑區')
    zone.append('石碇區')
    zone.append('坪林區')
    zone.append('三芝區')
    zone.append('石門區')
    zone.append('八里區')
    zone.append('平溪區')
    zone.append('雙溪區')
    zone.append('貢寮區')
    zone.append('金山區')
    zone.append('萬里區')
    zone.append('烏來區')
    county.append(['新北市', zone,470,100])
    
    zone = []
    zone.append('松山區')
    zone.append('信義區')
    zone.append('大安區')
    zone.append('中山區')
    zone.append('中正區')
    zone.append('大同區')
    zone.append('萬華區')
    zone.append('文山區')
    zone.append('南港區')
    zone.append('內湖區')
    zone.append('士林區')
    zone.append('北投區')    
    county.append(['臺北市', zone,470,70])
    
    zone = []
    zone.append('桃園區')
    zone.append('中壢區')
    zone.append('大溪區')
    zone.append('楊梅區')
    zone.append('蘆竹區')
    zone.append('大園區')
    zone.append('龜山區')
    zone.append('八德區')
    zone.append('龍潭區')
    zone.append('平鎮區')
    zone.append('新屋區')
    zone.append('觀音區')
    zone.append('復興區')    
    county.append(['桃園市', zone,330,85])
    
    zone = []
    zone.append('中　區')
    zone.append('東　區')
    zone.append('南　區')
    zone.append('西　區')
    zone.append('北　區')
    zone.append('西屯區')
    zone.append('南屯區')
    zone.append('北屯區')
    zone.append('豐原區')
    zone.append('東勢區')
    zone.append('大甲區')
    zone.append('清水區')
    zone.append('沙鹿區')
    zone.append('梧棲區')
    zone.append('后里區')
    zone.append('神岡區')
    zone.append('潭子區')
    zone.append('大雅區')
    zone.append('新社區')
    zone.append('石岡區')
    zone.append('外埔區')
    zone.append('大安區')
    zone.append('烏日區')
    zone.append('大肚區')
    zone.append('龍井區')
    zone.append('霧峰區')
    zone.append('太平區')
    zone.append('大里區')
    zone.append('和平區')    
    county.append(['臺中市', zone,240,250])
    
    zone = []
    zone.append('新營區')
    zone.append('鹽水區')
    zone.append('白河區')
    zone.append('柳營區')
    zone.append('後壁區')
    zone.append('東山區')
    zone.append('麻豆區')
    zone.append('下營區')
    zone.append('六甲區')
    zone.append('官田區')
    zone.append('大內區')
    zone.append('佳里區')
    zone.append('學甲區')
    zone.append('西港區')
    zone.append('七股區')
    zone.append('將軍區')
    zone.append('北門區')
    zone.append('新化區')
    zone.append('善化區')
    zone.append('新市區')
    zone.append('安定區')
    zone.append('山上區')
    zone.append('玉井區')
    zone.append('楠西區')
    zone.append('南化區')
    zone.append('左鎮區')
    zone.append('仁德區')
    zone.append('歸仁區')
    zone.append('關廟區')
    zone.append('龍崎區')
    zone.append('永康區')
    zone.append('東　區')
    zone.append('南　區')
    zone.append('北　區')
    zone.append('安南區')
    zone.append('安平區')
    zone.append('中西區')    
    county.append(['臺南市', zone,140,485])
		
    zone = []
    zone.append('鹽埕區')
    zone.append('鼓山區')
    zone.append('左營區')
    zone.append('楠梓區')
    zone.append('三民一')
    zone.append('三民二')
    zone.append('新興區')
    zone.append('前金區')
    zone.append('苓雅區')
    zone.append('前鎮區')
    zone.append('旗津區')
    zone.append('小港區')
    zone.append('鳳山一')
    zone.append('鳳山二')
    zone.append('林園區')
    zone.append('大寮區')
    zone.append('大樹區')
    zone.append('大社區')
    zone.append('仁武區')
    zone.append('鳥松區')
    zone.append('岡山區')
    zone.append('橋頭區')
    zone.append('燕巢區')
    zone.append('田寮區')
    zone.append('阿蓮區')
    zone.append('路竹區')
    zone.append('湖內區')
    zone.append('茄萣區')
    zone.append('永安區')
    zone.append('彌陀區')
    zone.append('梓官區')
    zone.append('旗山區')
    zone.append('美濃區')
    zone.append('六龜區')
    zone.append('甲仙區')
    zone.append('杉林區')
    zone.append('內門區')
    zone.append('茂林區')
    zone.append('桃源區')
    zone.append('那瑪夏區')    
    county.append(['高雄市', zone,230,515])

    zone = []
    zone.append('宜蘭市')
    zone.append('羅東鎮')
    zone.append('蘇澳鎮')
    zone.append('頭城鎮')
    zone.append('礁溪鄉')
    zone.append('壯圍鄉')
    zone.append('員山鄉')
    zone.append('冬山鄉')
    zone.append('五結鄉')
    zone.append('三星鄉')
    zone.append('大同鄉')
    zone.append('南澳鄉')    
    county.append(['宜蘭縣', zone,450,190])
	  
    zone = [] 
    zone.append('竹北市')
    zone.append('關西鎮')
    zone.append('新埔鎮')
    zone.append('竹東鎮')
    zone.append('湖口鄉')
    zone.append('橫山鄉')
    zone.append('新豐鄉')
    zone.append('芎林鄉')
    zone.append('寶山鄉')
    zone.append('北埔鄉')
    zone.append('峨眉鄉')
    zone.append('尖石鄉')
    zone.append('五峰鄉')    
    county.append(['新竹縣', zone,360,155])

    zone = []
    zone.append('苗栗市')
    zone.append('頭份市')
    zone.append('苑裡鎮')
    zone.append('通霄鎮')
    zone.append('竹南鎮')
    zone.append('後龍鎮')
    zone.append('卓蘭鎮')
    zone.append('大湖鄉')
    zone.append('公館鄉')
    zone.append('銅鑼鄉')
    zone.append('南庄鄉')
    zone.append('頭屋鄉')
    zone.append('三義鄉')
    zone.append('西湖鄉')
    zone.append('造橋鄉')
    zone.append('三灣鄉')
    zone.append('獅潭鄉')
    zone.append('泰安鄉')   
    county.append(['苗栗縣', zone,290,200])
    	
    zone = []
    zone.append('彰化市')
    zone.append('員林市')
    zone.append('鹿港鎮')
    zone.append('和美鎮')
    zone.append('北斗鎮')
    zone.append('溪湖鎮')
    zone.append('田中鎮')
    zone.append('二林鎮')
    zone.append('線西鄉')
    zone.append('伸港鄉')
    zone.append('福興鄉')
    zone.append('秀水鄉')
    zone.append('花壇鄉')
    zone.append('芬園鄉')
    zone.append('大村鄉')
    zone.append('埔鹽鄉')
    zone.append('埔心鄉')
    zone.append('永靖鄉')
    zone.append('社頭鄉')
    zone.append('二水鄉')
    zone.append('田尾鄉')
    zone.append('埤頭鄉')
    zone.append('芳苑鄉')
    zone.append('大城鄉')
    zone.append('竹塘鄉')
    zone.append('溪州鄉')
    county.append(['彰化縣', zone,200,300])

    zone = []
    zone.append('南投市')
    zone.append('埔里鎮')
    zone.append('草屯鎮')
    zone.append('竹山鎮')
    zone.append('集集鎮')
    zone.append('名間鄉')
    zone.append('鹿谷鄉')
    zone.append('中寮鄉')
    zone.append('魚池鄉')
    zone.append('國姓鄉')
    zone.append('水里鄉')
    zone.append('信義鄉')
    zone.append('仁愛鄉')
    county.append(['南投縣', zone,300,330])
    
    zone = []
    zone.append('斗六市')
    zone.append('斗南鎮')
    zone.append('虎尾鎮')
    zone.append('西螺鎮')
    zone.append('土庫鎮')
    zone.append('北港鎮')
    zone.append('古坑鄉')
    zone.append('大埤鄉')
    zone.append('莿桐鄉')
    zone.append('林內鄉')
    zone.append('二崙鄉')
    zone.append('崙背鄉')
    zone.append('麥寮鄉')
    zone.append('東勢鄉')
    zone.append('褒忠鄉')
    zone.append('臺西鄉')
    zone.append('元長鄉')
    zone.append('四湖鄉')
    zone.append('口湖鄉')
    zone.append('水林鄉')	
    county.append(['雲林縣', zone,150,370])

    zone = []
    zone.append('太保市')
    zone.append('朴子市')
    zone.append('布袋鎮')
    zone.append('大林鎮')
    zone.append('民雄鄉')
    zone.append('溪口鄉')
    zone.append('新港鄉')
    zone.append('六腳鄉')
    zone.append('東石鄉')
    zone.append('義竹鄉')
    zone.append('鹿草鄉')
    zone.append('水上鄉')
    zone.append('中埔鄉')
    zone.append('竹崎鄉')
    zone.append('梅山鄉')
    zone.append('番路鄉')
    zone.append('大埔鄉')
    zone.append('阿里山鄉')	
    county.append(['嘉義縣', zone,250,430])

    zone = []
    zone.append('屏東市')
    zone.append('潮州鎮')
    zone.append('東港鎮')
    zone.append('恆春鎮')
    zone.append('萬丹鄉')
    zone.append('長治鄉')
    zone.append('麟洛鄉')
    zone.append('九如鄉')
    zone.append('里港鄉')
    zone.append('鹽埔鄉')
    zone.append('高樹鄉')
    zone.append('萬巒鄉')
    zone.append('內埔鄉')
    zone.append('竹田鄉')
    zone.append('新埤鄉')
    zone.append('枋寮鄉')
    zone.append('新園鄉')
    zone.append('崁頂鄉')
    zone.append('林邊鄉')
    zone.append('南州鄉')
    zone.append('佳冬鄉')
    zone.append('琉球鄉')
    zone.append('車城鄉')
    zone.append('滿州鄉')
    zone.append('枋山鄉')
    zone.append('三地門鄉')
    zone.append('霧臺鄉')
    zone.append('瑪家鄉')
    zone.append('泰武鄉')
    zone.append('來義鄉')
    zone.append('春日鄉')
    zone.append('獅子鄉')
    zone.append('牡丹鄉')
    county.append(['屏東縣', zone,250,600])

    zone = [] 
    zone.append('臺東市')
    zone.append('成功鎮')
    zone.append('關山鎮')
    zone.append('卑南鄉')
    zone.append('大武鄉')
    zone.append('太麻里鄉')
    zone.append('東河鄉')
    zone.append('長濱鄉')
    zone.append('鹿野鄉')
    zone.append('池上鄉')
    zone.append('綠島鄉')
    zone.append('延平鄉')
    zone.append('海端鄉')
    zone.append('達仁鄉')
    zone.append('金峰鄉')
    zone.append('蘭嶼鄉')		
    county.append(['臺東縣', zone,320,550])
	
    zone = []
    zone.append('花蓮市')
    zone.append('鳳林鎮')
    zone.append('玉里鎮')
    zone.append('新城鄉')
    zone.append('吉安鄉')
    zone.append('壽豐鄉')
    zone.append('光復鄉')
    zone.append('豐濱鄉')
    zone.append('瑞穗鄉')
    zone.append('富里鄉')
    zone.append('秀林鄉')
    zone.append('萬榮鄉')
    zone.append('卓溪鄉')	
    county.append(['花蓮縣', zone,410,360])

    zone = []
    zone.append('馬公市')
    zone.append('湖西鄉')
    zone.append('白沙鄉')
    zone.append('西嶼鄉')
    zone.append('望安鄉')
    zone.append('七美鄉')	
    county.append(['澎湖縣', zone,20,390])
		
    zone = []
    zone.append('中正區')
    zone.append('七堵區')
    zone.append('暖暖區')
    zone.append('仁愛區')
    zone.append('中山區')
    zone.append('安樂區')
    zone.append('信義區')	
    county.append(['基隆市', zone,480,45])
	
    zone = []
    zone.append('東　區')
    zone.append('北　區')
    zone.append('香山區')	
    county.append(['新竹市', zone,300,125])
	
    zone = []
    zone.append('東　區')
    zone.append('市西　區')	
    county.append(['嘉義市', zone,200,410])
	
    zone = []
    zone.append('金城鎮')
    zone.append('金湖鎮')
    zone.append('金沙鎮')
    zone.append('金寧鄉')
    zone.append('縣烈嶼鄉')
    zone.append('縣烏坵鄉')	
    county.append(['金門縣', zone,50,205])
	
    zone = []
    zone.append('南竿鄉')
    zone.append('北竿鄉')
    zone.append('莒光鄉')
    zone.append('東引鄉')	
    county.append(['連江縣', zone,50,85])		
reset()

