# -*- coding: UTF-8 -*-
lesson_list1 = []
lesson_list2 = []
lesson_list3 = []

def reset():
    lesson_list1.append(["1","第1堂課：Scratch基本介紹","範例：綜合應用"])
    lesson_list1.append(["2","第2堂課：第一個動畫故事","範例：第一個動畫"])
    lesson_list1.append(["3-1","第3堂課：計次式迴圈","範例：馬兒跑步"])
    lesson_list1.append(["3-2","第3堂課：計次式迴圈","練習：變大變小"])
    lesson_list1.append(["4-1","第4堂課：條件式迴圈","範例：貓狗賽跑"])
    lesson_list1.append(["4-2","第4堂課：條件式迴圈","練習：發球"])
    lesson_list1.append(["5-1","第5堂課：無窮迴圈","範例：魚兒水中游"])
    lesson_list1.append(["5-2","第5堂課：無窮迴圈","練習：不斷發球"])
    lesson_list1.append(["6-1","第6堂課：單向選擇結構","範例：電流急急棒"])
    lesson_list1.append(["6-2","第6堂課：單向選擇結構","練習：開車"])
    lesson_list1.append(["7-1","第7堂課：雙向選擇結構","範例：打地鼠"])
    lesson_list1.append(["7-2","第7堂課：雙向選擇結構","練習：密碼檢查"])
    lesson_list1.append(["8","第8堂課：全域變數","範例：猴子吃香蕉"])
    lesson_list1.append(["9","第9堂課：全域變數","範例：打魔鬼"])
    lesson_list1.append(["10","第10堂課：角色變數","範例：射蝙蝠"])
    lesson_list1.append(["11~12","第11~12堂課：角色變數","範例：養魚"])
    lesson_list1.append(["12","第12堂課：角色變數","範例：打磚塊"])
    lesson_list1.append(["A01","實戰入門","接雞蛋"])
    lesson_list1.append(["A02","實戰入門","電流急急棒"])
    lesson_list1.append(["A03","實戰入門","打磚塊"])
    lesson_list1.append(["A04","實戰入門","打蟑螂"])
    lesson_list1.append(["A05","實戰入門","猜數字"])
    lesson_list1.append(["A06","實戰入門","射氣球"])
    lesson_list1.append(["A07","實戰入門","猴子吃香蕉"])
    lesson_list1.append(["A08","實戰入門","聖誕老公公送禮物"])
    lesson_list1.append(["B01","實戰進擊","小蜜蜂對抗戰"])
    lesson_list1.append(["B02","實戰進擊","貓貓大戰"])
    lesson_list1.append(["B03","實戰進擊","夾娃娃"])
    lesson_list1.append(["B04","實戰進擊","小章魚快快游"])
    lesson_list1.append(["B05","實戰進擊","緊急救援"])
    lesson_list1.append(["B06","實戰進擊","大魚吃小魚"])
    lesson_list1.append(["B07","實戰進擊","猜拳"])
    lesson_list1.append(["B08","實戰進擊","搶救貓咪"])	
    lesson_list1.append(["C01","實戰高手","跳遠"])
    lesson_list1.append(["C02","實戰高手","對對碰"])
    lesson_list1.append(["C03","實戰高手","水果盤"])
    lesson_list1.append(["C04","實戰高手","簡易接龍"])
    lesson_list1.append(["C05","實戰高手","星際大戰"])
    lesson_list1.append(["C06","實戰高手","貪食蛇"])
    lesson_list1.append(["C07","實戰高手","九宮拼圖"])
    lesson_list1.append(["C08","實戰高手","見縫插針"])    
    
    lesson_list2.append(["1-1", "VPhyscis移動"])
    lesson_list2.append(["1-2", "繞邊邊跑一圈"])
    lesson_list2.append(["2","一維等速運動"])   
    lesson_list2.append(["3","自由落體"])  
    lesson_list2.append(["4","兩牆間反彈"])  
    lesson_list2.append(["5","向量合成"])  
    lesson_list2.append(["6","速度視覺化"])  
    lesson_list2.append(["7","等速率圓周運動"])  
    lesson_list2.append(["8","畫時間位置圖"])  
    lesson_list2.append(["9","虎克定律"])  
    lesson_list2.append(["10","垂直簡諧運動"])  
    lesson_list2.append(["11","滾動的球"])  
    lesson_list2.append(["12","動量"])  
    lesson_list2.append(["13","彈性碰撞"])  
    lesson_list2.append(["14","三顆球追撞"])
    lesson_list2.append(["15","簡易牛頓擺"])
    lesson_list2.append(["16","行星公轉"])  	
    lesson_list2.append(["17","挑戰題"])
    lesson_list2.append(["18","專題製作"])  	
    
    lesson_list3.append(["1","倍數和"])
    lesson_list3.append(["2","費式數列"])  	
    lesson_list3.append(["6","平方和"])
    lesson_list3.append(["16","乘方數字和"])  
    lesson_list3.append(["20","階乘數字和"])  
    lesson_list3.append(["19","計算星期數"])	
    lesson_list3.append(["13","長整數相加"])  	
    lesson_list3.append(["9","畢式三元數"])
    lesson_list3.append(["7","質數"])  
    lesson_list3.append(["10","質數和"])  
    lesson_list3.append(["3","質因數"])
    lesson_list3.append(["5","最小公倍數"])  	
    lesson_list3.append(["8","數字連乘"])
    lesson_list3.append(["11","數字連乘"])  
    lesson_list3.append(["4","回文數"])  
    lesson_list3.append(["12","三角數"])
    lesson_list3.append(["15","格子路徑"])  	
    lesson_list3.append(["18","最大路徑和"])
    lesson_list3.append(["17","英文字母數"])  
    lesson_list3.append(["14","考拉茲猜想"])      
reset()