# -*- coding: UTF-8 -*-
def reset():

    lesson_list1 = []
    lesson_list2 = []
    lesson_list3 = []
    lesson_list4 = []
    lesson_list5 = []
    lesson_list6 = []
    lesson_list7 = []
    lesson_list = []

    lesson_list.append(['基礎程式設計：使用Scratch 3.X', []])
    lesson_list[0][1].append(['基礎篇', []])
    #--------------------------------名稱-----,檔案下載,編號,官網作品編號, tab, Youtube
    lesson_list[0][1][0][1].append(['教材：貓狗對話', False, 1, 199354464, False, False])
    lesson_list[0][1][0][1].append(['習作：勇者鬥惡龍', False, 2, 199356271, False, False])    
    lesson_list[0][1].append(['計算篇', []])
    lesson_list[0][1][1][1].append(['教材：求平均數', False, 3, 201792802, ["流程圖", "2_1.png"], False])          
    lesson_list[0][1][1][1].append(['教材：成績計算', False, 4, 201793143, ["流程圖", "2_2.png"], False])     
    lesson_list[0][1][1][1].append(['教材：累加計算', False, 5, 201793794, ["流程圖", "2_3.png"], False])    
    lesson_list[0][1][1][1].append(['教材：累乘計算', False, 6, 201794048, ["流程圖", "2_4.png"], False])  
    lesson_list[0][1][1][1].append(['教材：密碼檢查', False, 7, 201794208, ["流程圖", "2_5.png"], False])    
    lesson_list[0][1][1][1].append(['習作：溫度換算', False, 8, 201792945, [], False])
    lesson_list[0][1][1][1].append(['習作：書店打折', False, 9, 201793454, [], False])                
    lesson_list[0][1].append(['繪圖篇', []])
    lesson_list[0][1][2][1].append(['教材：畫方形', False, 10, 201791759, False, False])       
    lesson_list[0][1][2][1].append(['教材：擴散方形', False, 11, 201792210, False, False])         
    lesson_list[0][1][2][1].append(['教材：旋轉方形', False, 12, 201792359, False, False])    
    lesson_list[0][1][2][1].append(['習作：畫星星', False, 13, 201791984, False, False])      
    lesson_list[0][1][2][1].append(['習作：放大方形', False, 14, 201792631, False, False])  
    lesson_list[0][1][2][1].append(['習作：平行方形', False, 15, 201792490, False, False])                 
    lesson_list[0][1].append(['遊戲篇', []])
    lesson_list[0][1][3][1].append(['教材：狗狗散步', False, 16, 212207324, ["心智圖", "4_1.png"], False])  
    lesson_list[0][1][3][1].append(['教材：賽馬', False, 17, 212208431, ["心智圖", "4_2.png"], False])  
    lesson_list[0][1][3][1].append(['教材：水族箱', False, 18, 290858812, ["心智圖", "4_3.png"], False])  
    lesson_list[0][1][3][1].append(['教材：大馬路', False, 19, 213986419, ["心智圖", "4_4.png"], False])      
    lesson_list[0][1][3][1].append(['教材：打擊魔鬼', "1_20.zip", 20, 213986594, ["心智圖", "4_5.png"], False])
    lesson_list[0][1][3][1].append(['習作：打地鼠', False, 21, 216179680, ["心智圖", "6_5.png"], False])  
    lesson_list[0][1][3][1].append(['習作：打雷', "1_22.zip", 22, 201575317, ["心智圖", "4_6.png"], False])            
    lesson_list[0][1].append(['模擬篇', []])
    lesson_list[0][1][4][1].append(['教材：電子琴', "1_23.zip", 23, 201575462, False, False])  
    lesson_list[0][1][4][1].append(['教材：電梯', "1_24.zip", 24, 201575481, False, False])

    lesson_list1.append(["1",u"第1堂課：Scratch基本介紹",u"範例：綜合應用"])
    lesson_list1.append(["2",u"第2堂課：第一個動畫故事",u"範例：第一個動畫"])
    lesson_list1.append(["3-1",u"第3堂課：計次式迴圈",u"範例：馬兒跑步"])
    lesson_list1.append(["3-2",u"第3堂課：計次式迴圈",u"練習：變大變小"])
    lesson_list1.append(["4-1",u"第4堂課：條件式迴圈",u"範例：貓狗賽跑"])
    lesson_list1.append(["4-2",u"第4堂課：條件式迴圈",u"練習：發球"])
    lesson_list1.append(["5-1",u"第5堂課：無窮迴圈",u"範例：魚兒水中游"])
    lesson_list1.append(["5-2",u"第5堂課：無窮迴圈",u"練習：不斷發球"])
    lesson_list1.append(["6-1",u"第6堂課：單向選擇結構",u"範例：電流急急棒"])
    lesson_list1.append(["6-2",u"第6堂課：單向選擇結構",u"練習：開車"])
    lesson_list1.append(["7-1",u"第7堂課：雙向選擇結構",u"範例：打地鼠"])
    lesson_list1.append(["7-2",u"第7堂課：雙向選擇結構",u"練習：密碼檢查"])
    lesson_list1.append(["8",u"第8堂課：全域變數",u"範例：猴子吃香蕉"])
    lesson_list1.append(["9",u"第9堂課：全域變數",u"範例：打魔鬼"])
    lesson_list1.append(["10",u"第10堂課：角色變數",u"範例：射蝙蝠"])
    lesson_list1.append(["11~12",u"第11~12堂課：角色變數",u"範例：養魚"])
    lesson_list1.append(["12",u"第12堂課：角色變數",u"範例：打磚塊"])
    lesson_list1.append(["A01",u"實戰入門",u"接雞蛋"])
    lesson_list1.append(["A02",u"實戰入門",u"電流急急棒"])
    lesson_list1.append(["A03",u"實戰入門",u"打磚塊"])
    lesson_list1.append(["A04",u"實戰入門",u"打蟑螂"])
    lesson_list1.append(["A05",u"實戰入門",u"猜數字"])
    lesson_list1.append(["A06",u"實戰入門",u"射氣球"])
    lesson_list1.append(["A07",u"實戰入門",u"猴子吃香蕉"])
    lesson_list1.append(["A08",u"實戰入門",u"聖誕老公公送禮物"])
    lesson_list1.append(["B01",u"實戰進擊",u"小蜜蜂對抗戰"])
    lesson_list1.append(["B02",u"實戰進擊",u"貓貓大戰"])
    lesson_list1.append(["B03",u"實戰進擊",u"夾娃娃"])
    lesson_list1.append(["B04",u"實戰進擊",u"小章魚快快游"])
    lesson_list1.append(["B05",u"實戰進擊",u"緊急救援"])
    lesson_list1.append(["B06",u"實戰進擊",u"大魚吃小魚"])
    lesson_list1.append(["B07",u"實戰進擊",u"猜拳"])
    lesson_list1.append(["B08",u"實戰進擊",u"搶救貓咪"])	
    lesson_list1.append(["C01",u"實戰高手",u"跳遠"])
    lesson_list1.append(["C02",u"實戰高手",u"對對碰"])
    lesson_list1.append(["C03",u"實戰高手",u"水果盤"])
    lesson_list1.append(["C04",u"實戰高手",u"簡易接龍"])
    lesson_list1.append(["C05",u"實戰高手",u"星際大戰"])
    lesson_list1.append(["C06",u"實戰高手",u"貪食蛇"])
    lesson_list1.append(["C07",u"實戰高手",u"九宮拼圖"])
    lesson_list1.append(["C08",u"實戰高手",u"見縫插針"])    
    
    lesson_list2.append(["1-1", "VPhyscis移動"])
    lesson_list2.append(["1-2", "繞邊邊跑一圈"])
    lesson_list2.append(["2",u"一維等速運動"])   
    lesson_list2.append(["3",u"自由落體"])  
    lesson_list2.append(["4",u"兩牆間反彈"])  
    lesson_list2.append(["5",u"向量合成"])  
    lesson_list2.append(["6",u"速度視覺化"])  
    lesson_list2.append(["7",u"等速率圓周運動"])  
    lesson_list2.append(["8",u"畫時間位置圖"])  
    lesson_list2.append(["9",u"虎克定律"])  
    lesson_list2.append(["10",u"垂直簡諧運動"])  
    lesson_list2.append(["11",u"滾動的球"])  
    lesson_list2.append(["12",u"動量"])  
    lesson_list2.append(["13",u"彈性碰撞"])  
    lesson_list2.append(["14",u"三顆球追撞"])
    lesson_list2.append(["15",u"簡易牛頓擺"])
    lesson_list2.append(["16",u"行星公轉"])  	
    lesson_list2.append(["17",u"挑戰題"])
    lesson_list2.append(["18",u"專題製作"])  	
    
    lesson_list3.append(["1",u"倍數和"])
    lesson_list3.append(["2",u"費式數列"])  	
    lesson_list3.append(["6",u"平方和"])
    lesson_list3.append(["16",u"乘方數字和"])  
    lesson_list3.append(["20",u"階乘數字和"])  
    lesson_list3.append(["19",u"計算星期數"])	
    lesson_list3.append(["13",u"長整數相加"])  	
    lesson_list3.append(["9",u"畢式三元數"])
    lesson_list3.append(["7",u"質數"])  
    lesson_list3.append(["10",u"質數和"])  
    lesson_list3.append(["3",u"質因數"])
    lesson_list3.append(["5",u"最小公倍數"])  	
    lesson_list3.append(["8",u"數字連乘"])
    lesson_list3.append(["11",u"數字連乘"])  
    lesson_list3.append(["4",u"回文數"])  
    lesson_list3.append(["12",u"三角數"])
    lesson_list3.append(["15",u"格子路徑"])  	
    lesson_list3.append(["18",u"最大路徑和"])
    lesson_list3.append(["17",u"英文字母數"])  
    lesson_list3.append(["14",u"考拉茲猜想"])   
    
    lesson_list4.append(["1",u"迴圈與物件控制"])
    lesson_list4.append(["2",u"F=ma的數值解"])   
    lesson_list4.append(["3",u"圓周運動"])  
    lesson_list4.append(["4",u"碰撞"])  
    lesson_list4.append(["5",u"克卜勒定律"])  
    lesson_list4.append(["6",u"三行星運動"])  
    lesson_list4.append(["7",u"多物件控制"])  
    lesson_list4.append(["8",u"多物件進階"])  
    lesson_list4.append(["9",u"多物件應用"])  
    lesson_list4.append(["10",u"鍵盤與滑鼠控制"])  
    
    lesson_list5.append(["1",u"HTML基礎"])
    lesson_list5.append(["2",u"Python基礎"])   
    lesson_list5.append(["3",u"安裝與架站"])  
    lesson_list5.append(["4",u"專案與應用程式"])  
    lesson_list5.append(["5",u"與資料庫互動"])  
    lesson_list5.append(["6",u"視圖網址範本"])  
    lesson_list5.append(["7",u"使用者表單"])  
    lesson_list5.append(["8",u"實戰：留言板"])  
    lesson_list5.append(["9",u"實戰：日誌"])  
    lesson_list5.append(["10",u"實戰：記帳"])    
    lesson_list5.append(["11",u"CSS基礎"])    
    lesson_list5.append(["12",u"JavaScript基礎"])   
    lesson_list5.append(["13",u"響應式網頁"])    
    lesson_list5.append(["14",u"案例：投票"])  
    lesson_list5.append(["15",u"案例：留言板"])  
    lesson_list5.append(["16",u"案例：數位助理"])  
    lesson_list5.append(["17",u"GitHub分享"])  
    lesson_list5.append(["18",u"Heroku發佈"])    

    lesson_list6.append(["1",u"閃爍的愛心"])   
    lesson_list6.append(["2",u"顯示數字"])      
    lesson_list6.append(["3",u"顯示文字"])      
    lesson_list6.append(["4",u"按鈕數字"])      
    lesson_list6.append(["5",u"無線電廣播"])         
    lesson_list6.append(["6",u"閃燈"])      
    lesson_list6.append(["7",u"小夜燈"])      
    lesson_list6.append(["8",u"紅綠燈"])      
    lesson_list6.append(["9",u"直流馬達"])         
    lesson_list6.append(["10",u"超音波測距"])      
    lesson_list6.append(["11",u"超音波馬達"])      
    lesson_list6.append(["12",u"角度伺服馬達"])      
    lesson_list6.append(["13",u"按鈕小車前進"])         
    lesson_list6.append(["14",u"廣播遙控小車"])      
    lesson_list6.append(["15",u"搖桿遙控小車"])      
    lesson_list6.append(["16",u"智慧避障車"])                      

    lesson_list7.append(["1",u"可汗學院的教育奇蹟"])      
    lesson_list7.append(["2",u"創新是一種態度"])       
    lesson_list7.append(["3",u"大腦喜歡這樣學"])
    lesson_list7.append(["4",u"刻意練習"])
    lesson_list7.append(["5",u"學習就像終身幼兒園"])            
reset()