# Generated by Django 3.2.23 on 2023-11-30 03:04

import certificate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='picture',
            field=models.ImageField(default='/static/certificate/null.jpg', upload_to=certificate.models.upload_path_handler),
        ),
    ]
