# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-04-18 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_assistant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('lesson_id', models.IntegerField(default=0)),
                ('index', models.IntegerField()),
                ('memo', models.TextField()),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('score', models.IntegerField(default=-1)),
                ('scorer', models.IntegerField(default=0)),
                ('file', models.FileField(upload_to=b'')),
                ('picture', models.ImageField(default='/static/python/null.jpg', upload_to=student.models.upload_path_handler)),
                ('code', models.TextField(default='')),
                ('helps', models.IntegerField(default=0)),
                ('answer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorkFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.IntegerField(default=0)),
                ('filename', models.TextField()),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
