# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-04-18 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_work_workfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assistant',
            new_name='WorkAssistant',
        ),
    ]
