# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-04-19 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20180419_0416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(default=0)),
                ('lesson_id', models.IntegerField(default=0)),
                ('index', models.IntegerField()),
            ],
        ),
    ]
