# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-06-11 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20180419_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='certificate_euler',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enroll',
            name='certificate_euler_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='enroll',
            name='certificate_vphysics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enroll',
            name='certificate_vphysics_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='enroll',
            name='score_memo_euler',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enroll',
            name='score_memo_vphysics',
            field=models.IntegerField(default=0),
        ),
    ]
