# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-06-27 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20180624_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('answer', models.TextField()),
                ('score', models.IntegerField()),
            ],
        ),
    ]
