# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-06-27 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='test_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
