# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-06-29 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_exam_test_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='typing',
            field=models.IntegerField(default=0),
        ),
    ]
