# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-06-30 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_workassistant_typing'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='score_memo',
            field=models.IntegerField(default=0),
        ),
    ]
