# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-06-30 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_enroll_score_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='certificate_vphysics2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enroll',
            name='certificate_vphysics2_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='enroll',
            name='score_memo_vphysics2',
            field=models.IntegerField(default=0),
        ),
    ]
