# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-06-30 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_auto_20180701_0709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enroll',
            old_name='groups',
            new_name='groupshow',
        ),
    ]
