# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-06-30 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_auto_20180701_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='groupshow',
            field=models.CommaSeparatedIntegerField(max_length=200),
        ),
    ]
