# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-07-08 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_auto_20180701_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='certificate_vphysics3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enroll',
            name='certificate_vphysics3_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='enroll',
            name='score_memo_vphysics3',
            field=models.IntegerField(default=0),
        ),
    ]
