# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 09:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_work_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='groupshow',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
