# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-25 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_auto_20180822_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='certificate_microbit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enroll',
            name='certificate_microbit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='enroll',
            name='score_memo_microbit',
            field=models.IntegerField(default=0),
        ),
    ]
