# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-15 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_merge_20180825_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='SFContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('student_id', models.IntegerField(default=0)),
                ('work_id', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('filename', models.CharField(blank=True, max_length=60, null=True)),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('delete_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SFReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('work_id', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
                ('memo', models.TextField(default='')),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SFWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(default=0)),
                ('index', models.IntegerField()),
                ('memo', models.TextField(default='')),
                ('memo_e', models.IntegerField(default=0)),
                ('memo_c', models.IntegerField(default=0)),
                ('publish', models.BooleanField(default=False)),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reply_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('score', models.IntegerField(default=0)),
                ('scorer', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True, default='', null=True)),
                ('comment_publication_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('likes', models.TextField(default='')),
                ('like_count', models.IntegerField(default=0)),
                ('reply', models.IntegerField(default=0)),
            ],
        ),
    ]
