# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-29 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0025_auto_20180928_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Science3Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(default=0)),
                ('lesson', models.IntegerField(default=0)),
                ('typing', models.IntegerField(default=0)),
                ('index', models.IntegerField()),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('picture', models.ImageField(default='/static/python/null.jpg', upload_to=student.models.upload_path_handler)),
                ('code', models.TextField(default='')),
            ],
        ),
    ]
