# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-29 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_science3work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Science4Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.IntegerField(default=0)),
                ('types', models.IntegerField(default=0)),
                ('text', models.TextField(default='')),
                ('pic', models.FileField(blank=True, null=True, upload_to=b'')),
                ('picname', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
