# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0028_science4work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Science2Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('student_id', models.IntegerField(default=0)),
                ('types', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
