# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0029_science2data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Science1Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twork_id', models.IntegerField(default=0)),
                ('question', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='science1work',
            name='question_id',
            field=models.IntegerField(default=0),
        ),
    ]
