# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-15 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0031_auto_20181004_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Science2Expression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('student_id', models.IntegerField(default=0)),
                ('expr_json', models.TextField(default='{vars:[], arrs:[], strs:[], nums:[], exprs:[]}')),
            ],
        ),
    ]
