# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0032_science2expression'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='certificate_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enroll',
            name='certificate_custom_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='enroll',
            name='score_memo_custom',
            field=models.IntegerField(default=0),
        ),
    ]
