# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0033_auto_20181022_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enroll',
            name='certificate_custom',
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='certificate_custom_date',
        ),
        migrations.AddField(
            model_name='enroll',
            name='score_memo_check',
            field=models.IntegerField(default=0),
        ),
    ]
