# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-03 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0034_auto_20181022_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Science2Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('student_id', models.IntegerField(default=0)),
                ('flow_json', models.TextField(default='[]')),
            ],
        ),
        migrations.AlterField(
            model_name='science2expression',
            name='expr_json',
            field=models.TextField(default='{vars:[], arrs:[], exprs:[]}'),
        ),
    ]
