# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 14:23
from __future__ import unicode_literals

from django.db import migrations, models

def migrate_expression(apps, schema_editor):
    Science2Expression = apps.get_model("student", "Science2Expression")
    Science2Flow = apps.get_model("student", "Science2Flow")
    Science2Json = apps.get_model("student", "Science2Json")
    db_alias = schema_editor.connection.alias
    exprs = Science2Expression.objects.all()
    flows = Science2Flow.objects.all()
    for exp in exprs:
        json = Science2Json(index=exp.index, student_id=exp.student_id, model_type=0, json=exp.expr_json)
        json.save()
    for flow in flows:
        json = Science2Json(index=flow.index, student_id=flow.student_id, model_type=1, json=flow.flow_json)
        json.save()

class Migration(migrations.Migration):

    dependencies = [
        ('student', '0035_auto_20181103_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Science2Json',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('student_id', models.IntegerField(default=0)),
                ('model_type', models.IntegerField(default=0)),
                ('json', models.TextField(default='')),
            ],
        ),
        migrations.RunPython(migrate_expression),
    ]
