# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0037_auto_20181105_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
