# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-30 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0038_work_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='science3work',
            name='helps',
            field=models.IntegerField(choices=[(0, '\u5168\u90e8\u9760\u81ea\u5df1\u60f3'), (1, '\u540c\u5b78\u5e6b\u4e00\u9ede\u5fd9'), (2, '\u540c\u5b78\u5e6b\u5f88\u591a\u5fd9'), (3, '\u8001\u5e2b\u5e6b\u4e00\u9ede\u5fd9'), (4, '\u8001\u5e2b\u5e6b\u5f88\u591a\u5fd9')], default=0),
        ),
        migrations.AlterField(
            model_name='science3work',
            name='picture',
            field=models.ImageField(upload_to=b''),
        ),
    ]
