# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-30 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0039_auto_20181230_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Science4Debug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work3_id', models.IntegerField(default=0)),
                ('types', models.IntegerField(default=0)),
                ('bug', models.TextField(default='')),
                ('improve', models.TextField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='Science4Content',
        ),
        migrations.RemoveField(
            model_name='science4work',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='science4work',
            name='memo',
            field=models.TextField(default=''),
        ),
    ]
