# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-30 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0041_science4work_publication_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='science4debug',
            name='types',
        ),
        migrations.AddField(
            model_name='science4debug',
            name='bug_types',
            field=models.IntegerField(choices=[(0, '\u7a0b\u5f0f\u8a9e\u6cd5\u932f\u8aa4'), (1, '\u7a0b\u5f0f\u908f\u8f2f\u932f\u8aa4'), (2, '\u5176\u5b83')], default=0),
        ),
    ]
