# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-30 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0042_auto_20181230_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='science4debug',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
