# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-30 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0043_science4debug_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='score_memo_pandas',
            field=models.IntegerField(default=0),
        ),
    ]
