# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-01 04:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0047_auto_20190201_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enroll',
            old_name='group',
            new_name='group2',
        ),
    ]
