# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-19 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0049_enroll_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(default=0)),
                ('memo', models.TextField(default='')),
                ('filename', models.CharField(blank=True, max_length=20, null=True)),
                ('picture', models.ImageField(default='/static/python/null.jpg', upload_to=student.models.upload_path_handler_plant)),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='EnrollGroup',
        ),
    ]
