# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-19 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0050_auto_20190319_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='filename',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
