# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-17 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0052_plantlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(default=0)),
                ('filename', models.CharField(blank=True, max_length=50, null=True)),
                ('picture', models.ImageField(default='/static/python/null.jpg', upload_to=student.models.upload_path_handler_plantphoto)),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
