# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-17 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0053_plantphoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantphoto',
            old_name='picture',
            new_name='photo',
        ),
    ]
