# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-17 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0054_auto_20190417_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantphoto',
            old_name='photo',
            new_name='uploads',
        ),
    ]
