# Generated by Django 3.2.23 on 2023-11-30 03:04

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0055_auto_20190417_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='groupshow',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='science1content',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='science3work',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='work',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
