# Generated by Django 4.2.8 on 2023-12-13 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0019_alter_assistant_id_alter_classroom_id_alter_cwork_id_and_more'),
        ('student', '0057_alter_answer_id_alter_enroll_id_alter_exam_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enroll',
            old_name='classroom_id',
            new_name = 'classroom',
        ),
        migrations.AlterField(
            model_name='enroll',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enroll_list', to='teacher.classroom'),
        ),
        migrations.RenameField(
            model_name='enroll',
            old_name='student_id',
            new_name = 'student',
        ),
        migrations.AlterField(
            model_name='enroll',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enroll_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
