# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-06-24 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreSurvey2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(default=0)),
                ('fill_time', models.DateTimeField(auto_now_add=True)),
                ('p', models.IntegerField(default=0)),
                ('p_t', models.TextField()),
                ('p1', models.IntegerField(default=0)),
                ('p2', models.IntegerField(default=0)),
                ('p3', models.IntegerField(default=0)),
                ('p4', models.IntegerField(default=0)),
                ('p5', models.IntegerField(default=0)),
                ('p6', models.IntegerField(default=0)),
                ('p7', models.IntegerField(default=0)),
                ('p8', models.IntegerField(default=0)),
                ('p9', models.IntegerField(default=0)),
                ('p10', models.IntegerField(default=0)),
            ],
        ),
    ]
